version: '3.4'

services: 

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:DatabaseName=ProductDb"
      - "DatabaseSettings:CollectionName=Products"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
     - 27018:27017
    volumes:
      - mongo_data:/data/db

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379 

  portainer:
    container_name: portainer
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_volume
    restart: always

